networks:
  dfir-networks:
    name: dfir-automation-analysis
    driver: bridge

volumes:
  postgres:
    driver: local
    name: postgres
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  django:
    driver: local
    name: django
    driver_opts:
      type: none
      o: bind
      device: ./django
services:
  postgres:
    container_name: postgres
    image: postgres:16.2-bookworm
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dfir-networks
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - django:/home/django/
    networks:
      - dfir-networks
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
